server {
    listen 80;
    server_name caruaru.desentupidorape.com.br
                palmares.desentupidorape.com.br
                santa-cruz-do-capibaribe.desentupidorape.com.br
                bezerros.desentupidorape.com.br
                gravata.desentupidorape.com.br
                garanhuns.desentupidorape.com.br
                toritama.desentupidorape.com.br;

    root /home/desentupidoraprincipal/app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
