name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - name: Executando comando via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/app

            echo "→ Restaurando código"
            git checkout .
            git pull

            echo "→ Instalando dependências front-end"
            npm ci
            npm run build

            echo "→ Instalando dependências PHP"
            COMPOSER_ALLOW_SUPERUSER=1 composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "→ Rodando migrations"
            php artisan migrate --force